package io.totokaka.strikk.annotations;

import org.bukkit.plugin.java.JavaPlugin;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation for a plugin that should have it's plugin.yml generated by Strikk.
 *
 * <p>
 *     This annotation should only be applied to classes that extend {@link JavaPlugin},
 *     and there may only be one instance of this annotation for each compiled module.
 *     The info declared in the annotation will be used to generate the plugin.yml file.
 * </p>
 */
@Target({ElementType.TYPE})
@Retention(RetentionPolicy.CLASS)
public @interface StrikkPlugin {

    /**
     * The name of this plugin.
     *
     * <ul>
     *     <li>Must consist of alphanumeric characters and/or underscores</li>
     *     <li>Will determine the name of this plugins data folder</li>
     * </ul>
     *
     * @return the name of this plugin
     */
    String name();

    /**
     * The version of the plugin.
     *
     * <ul>
     *     <li>May be an arbitrary string, although Schematic Versioning is recommended</li>
     *     <li>Will be displayed with the /version &lt plugin &gt command</li>
     * </ul>
     *
     * @return The version of the plugin
     */
    String version();

    /**
     * A human readable description of the plugin.
     *
     * <ul>
     *     <li>May have multiple lines</li>
     *     <li>Will be displayed with the /version &lt plugin &gt command</li>
     * </ul>
     *
     * @return A human readable description of the plugin
     */
    String description() default "";

    /**
     * An unique identifier of the plugin author.
     *
     * <p>
     *     May be a name, nickname or email of the main developer. Will be merged into authors.
     * </p>
     *
     * @return An unique identifier of the main plugin Author
     */
    String author() default "";

    /**
     * List of contributors to the plugin.
     *
     * <p>
     *     Follows same rules as author, and will be merged with it.
     * </p>
     *
     * @return Contributors to the plugin
     */
    String[] authors() default {};

    /**
     * The plugin's or author's website.
     *
     * @return the plugin's or author's website
     */
    String website() default "";

    /**
     * When during startup the plugin should be loaded.
     *
     * @see LoadTime
     * @return when the plugin should be loaded
     */
    LoadTime load() default LoadTime.POST_WORLD;

    /**
     * Indicates whether this plugin uses the CraftBukkit server's database.
     *
     * <p>
     *     CraftBukkit servers provide a database that may be used by plugins,
     *     if this field is set true.
     * </p>
     *
     * @return Whether this plugin uses the CraftBukkit server's database
     */
    boolean database() default false;

    /**
     * A list of plugins this plugin depends on.
     *
     * <p>
     *     Other plugins are identified by their name. If not all these plugins
     *     are available at server start, this plugin will not be loaded.
     * </p>
     *
     * @return Plugins this plugin depends on
     */
    String[] depend() default {};

    /**
     * A list of plugins this plugin should load after.
     *
     * <p>
     *     Other plugins are identified by their name. This plugin will be loaded
     *     after the plugins specified here, if they exists on the server.
     * </p>
     *
     * @return Plugins this plugin soft depends on
     */
    String[] softDepend() default {};

    /**
     * A list of plugins this plugin should be loaded before.
     *
     * <p>
     *     The plugins listed here will be loaded after this plugin. The other plugins
     *     are identified by their name.
     * </p>
     *
     * @return A list of plugins that should be loaded after this plugin
     */
    String[] loadBefore() default {};

    /**
     * The logging prefix for this plugin's logger.
     *
     * @return The logging prefix
     */
    String prefix() default "";

}
